# Generated by Django 4.2.3 on 2023-08-28 13:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('work_unit', models.CharField(blank=True, max_length=100, null=True)),
                ('period', models.CharField(blank=True, max_length=4, null=True)),
                ('media', models.CharField(blank=True, max_length=50, null=True)),
                ('count', models.IntegerField(null=True)),
                ('save_life', models.CharField(blank=True, max_length=100, null=True)),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('save_location', models.TextField(blank=True, null=True)),
                ('protect_method', models.CharField(blank=True, max_length=100, null=True)),
                ('orinot', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('variety', models.ForeignKey(db_column='variety_id', on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='alihmedia_vital.variety')),
            ],
        ),
    ]
