# Generated by Django 4.2.3 on 2023-08-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alihmedia_vital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='count',
        ),
        migrations.AddField(
            model_name='doc',
            name='countstr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
