# Generated by Django 4.2.3 on 2023-08-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alihmedia_vital', '0002_remove_doc_count_doc_countstr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='orinot',
        ),
        migrations.AlterField(
            model_name='doc',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
