# Generated by Django 4.2.3 on 2023-08-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alihmedia_vital', '0004_variety_folder_alter_variety_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='doc_number',
            field=models.SmallIntegerField(null=True),
        ),
    ]
