# Generated by Django 4.2.3 on 2023-08-11 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alihmedia_inactive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='filepath',
            field=models.FileField(default=django.utils.timezone.now, upload_to='pdftmp/'),
            preserve_default=False,
        ),
    ]
