# Generated by Django 4.2.3 on 2023-08-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alihmedia_inactive', '0002_doc_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='filepath',
        ),
    ]
