# Generated by Django 4.2.3 on 2023-08-12 22:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('alihmedia_inactive', '0003_remove_doc_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='uuid_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
