# Generated by Django 4.2.3 on 2023-11-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_pjpa', '0003_alter_department_folder_alter_department_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='link',
        ),
        migrations.AddField(
            model_name='department',
            name='shortname',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='folder',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(default=None, max_length=40, unique=True),
        ),
    ]
