# Generated by Django 4.2.3 on 2023-11-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_pjpa', '0004_remove_department_link_department_shortname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
