# Generated by Django 4.2.3 on 2023-11-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_pjpa', '0005_file_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filesize',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='mime_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
