# Generated by Django 4.2.3 on 2023-11-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fm_pjpa', '0006_file_filesize_file_mime_type_alter_file_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='filesize',
        ),
        migrations.RemoveField(
            model_name='file',
            name='mime_type',
        ),
    ]
