# Generated by Django 4.2.3 on 2023-11-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm_pjpa', '0007_remove_file_filesize_remove_file_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subfolder',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
