# Generated by Django 4.2.3 on 2023-11-21 00:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('box_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bundle_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('code', models.CharField(max_length=10)),
                ('creator', models.CharField(max_length=255)),
                ('decription', models.TextField(blank=True, null=True)),
                ('year_bundle', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)])),
                ('box', models.ForeignKey(db_column='box_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='arsip_tata.box')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yeardate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2023), django.core.validators.MaxValueValidator(2050)])),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=255)),
                ('copy', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('original', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('total', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('accesstype', models.CharField(choices=[('B', 'Biasa'), ('T', 'Terbatas'), ('R', 'Rahasia')], default='T', max_length=2)),
                ('bundle', models.ForeignKey(db_column='bundle_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='arsip_tata.bundle')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='year',
            field=models.ForeignKey(db_column='year_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='arsip_tata.year'),
        ),
    ]
