# Generated by Django 4.2.3 on 2023-11-21 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip_tata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='yeardate',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2023), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AddConstraint(
            model_name='box',
            constraint=models.UniqueConstraint(fields=('box_number', 'year_id'), name='unique_box_number_year'),
        ),
    ]
