# Generated by Django 4.2.3 on 2023-11-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip_tata', '0002_alter_year_yeardate_box_unique_box_number_year'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bundle',
            constraint=models.UniqueConstraint(fields=('bundle_number', 'box_id'), name='unique_bundle_number_box'),
        ),
    ]
