# Generated by Django 4.2.3 on 2023-11-21 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip_tata', '0003_bundle_unique_bundle_number_box'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('item_number', 'bundle_id'), name='unique_item_number_bundle'),
        ),
    ]
