# Generated by Django 4.2.3 on 2023-08-13 13:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('box_number', models.SmallIntegerField()),
                ('bundle_number', models.SmallIntegerField()),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('orinot', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('defcode', models.CharField(max_length=20, unique=True)),
                ('link', models.CharField(max_length=50, unique=True)),
                ('folder', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_number', models.SmallIntegerField()),
                ('doc_count', models.SmallIntegerField(null=True)),
                ('orinot', models.CharField(blank=True, max_length=10, null=True)),
                ('doc_type', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('filesize', models.IntegerField(null=True)),
                ('page_count', models.SmallIntegerField(null=True)),
                ('uuid_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bundle', models.ForeignKey(db_column='bundle_id', on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='alihmedia_inactive.bundle')),
            ],
        ),
        migrations.AddField(
            model_name='bundle',
            name='department',
            field=models.ForeignKey(db_column='department_id', on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='alihmedia_inactive.department'),
        ),
    ]
